MyLocation002/Pages/Categories/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyLocation002.Data;
using MyLocation002.Data.Models;
using System.Threading.Tasks;

namespace MyLocation002.Pages.Categories
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public CreateModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty]
        public Category Categories { get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _dbContext.Categories.Add(Categories);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

MyLocation002/Pages/Categories/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyLocation002.Data;
using MyLocation002.Data.Models;
using System.Threading.Tasks;

namespace MyLocation002.Pages.Categories
{
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        [TempData]
        public string Message { get; set; }

        public DeleteModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Categories = await _dbContext.Categories.SingleOrDefaultAsync(w => w.Id == id);

            if (Categories == null)
            {
                return NotFound();
            }

            return Page();
        }

        [BindProperty]
        public Category Categories { get; set; }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Categories = await _dbContext.Categories.FindAsync(id);

            if (Categories != null)
            {
                _dbContext.Categories.Remove(Categories);

                await _dbContext.SaveChangesAsync();

                Message = "Item Was Deleted !";
            }

            return RedirectToPage("./Index");
        }
    }
}

MyLocation002/Pages/Categories/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyLocation002.Data;
using MyLocation002.Data.Models;
using System.Threading.Tasks;

namespace MyLocation002.Pages.Categories
{
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public DetailsModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty]
        public Category Categories { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Categories = await _dbContext.Categories.SingleOrDefaultAsync(w => w.Id == id);

            if (Categories == null)
            {
                return NotFound();
            }

            return Page();
        }
    }
}

MyLocation002/Pages/Categories/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyLocation002.Data;
using MyLocation002.Data.Models;
using System.Threading.Tasks;

namespace MyLocation002.Pages.Categories
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public EditModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty]
        public Category Categories { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Categories = await _dbContext.Categories.SingleOrDefaultAsync(w => w.Id == id);

            if (Categories == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _dbContext.Attach(Categories).State = EntityState.Modified;

            await _dbContext.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

MyLocation002/Pages/Locations/Create.cshtml.cs
using GoogleMaps.LocationServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyLocation002.Data;
using MyLocation002.Data.Models;
using MyLocation002.ViewModel;
using System.Linq;
using System.Threading.Tasks;

namespace MyLocation002.Pages.Locations
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;
        private GoogleLocationService _googleLocation;

        public CreateModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [TempData]
        public string Message { get; set; }

        [BindProperty]
        public LocationsViewModel LocationsVM { get; set; }

        public IActionResult OnGet()
        {
            LocationsVM = new LocationsViewModel()
            {
                Locations = new Location(),
                Categories = _dbContext.Categories.ToList()
            };

            return Page();
        }

        public async Task<IActionResult> OnPostCreateAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _dbContext.Locations.Add(LocationsVM.Locations);

            await _dbContext.SaveChangesAsync().ConfigureAwait(false);

            Message = "New Location Has Been Added!";

            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostFatchCordinates()
        {
            LocationsVM = new LocationsViewModel()
            {
                Locations = new Location()
                {
                    Name = LocationsVM.Locations.Name,
                    Adress = LocationsVM.Locations.Adress
                },
                Categories = await _dbContext.Categories.ToListAsync().ConfigureAwait(false)
            };

            _googleLocation = new GoogleLocationService();

            var name = LocationsVM.Locations.Name;
            var adress = LocationsVM.Locations.Adress;

            var point = _googleLocation.GetLatLongFromAddress(name + " " + adress);

            LocationsVM.Locations.Longitude = point.Longitude;
            LocationsVM.Locations.Latitude = point.Latitude;

            return Page();
        }
    }
}

MyLocation002/Pages/Locations/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyLocation002.Data;
using MyLocation002.Data.Models;
using System.Threading.Tasks;

namespace MyLocation002.Pages.Locations
{
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public DeleteModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [TempData]
        public string Message { get; set; }

        public async Task<IActionResult> OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Locations = await _dbContext.Locations.Include(w => w.Category).SingleOrDefaultAsync(w => w.Id == id).ConfigureAwait(false);

            if (Locations == null)
            {
                return NotFound();
            }

            return Page();
        }

        [BindProperty]
        public Location Locations { get; set; }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Locations = await _dbContext.Locations.FindAsync(id).ConfigureAwait(false);

            if (Locations != null)
            {
                _dbContext.Locations.Remove(Locations);

                await _dbContext.SaveChangesAsync().ConfigureAwait(false);

                Message = "Item Was Deleted !";
            }

            return RedirectToPage("./Index");
        }
    }
}

MyLocation002/Pages/Locations/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyLocation002.Data;
using MyLocation002.Data.Models;
using MyLocation002.ViewModel;
using System.Linq;
using System.Threading.Tasks;

namespace MyLocation002.Pages.Locations
{
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public DetailsModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty]
        public Location Locations { get; set; }

        [BindProperty]
        public LocationsViewModel LocationsVM { get; set; }


        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            LocationsVM = new LocationsViewModel()
            {
                Locations = await _dbContext.Locations.Include(w => w.Category).SingleOrDefaultAsync(w => w.Id == id),
                Categories = _dbContext.Categories.ToList()
            };

            if (LocationsVM.Locations == null)
            {
                return NotFound();
            }

            Locations = await _dbContext.Locations.SingleOrDefaultAsync(w => w.Id == id);

            if (Locations == null)
            {
                return NotFound();
            }

            return Page();
        }
    }
}

MyLocation002/Pages/Locations/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyLocation002.Data;
using MyLocation002.ViewModel;
using System.Linq;
using System.Threading.Tasks;

namespace MyLocation002.Pages.Locations
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public EditModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty]
        public LocationsViewModel LocationsVM { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            LocationsVM = new LocationsViewModel()
            {
                Locations = await _dbContext.Locations.Include(w => w.Category).SingleOrDefaultAsync(w => w.Id == id),
                Categories = _dbContext.Categories.ToList()
            };

            if (LocationsVM.Locations == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var locationItemFromDb = _dbContext.Locations.Where(w => w.Id == LocationsVM.Locations.Id).FirstOrDefault();

            if (!ModelState.IsValid)
            {
                return Page();
            }

            locationItemFromDb.Name = LocationsVM.Locations.Name;
            locationItemFromDb.CategoryId = LocationsVM.Locations.CategoryId;
            locationItemFromDb.Adress = LocationsVM.Locations.Adress;
            locationItemFromDb.Latitude = LocationsVM.Locations.Latitude;
            locationItemFromDb.Longitude = LocationsVM.Locations.Longitude;

            await _dbContext.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

MyLocation002/Pages/Locations/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyLocation002.Data;
using MyLocation002.Data.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyLocation002.Pages.Locations
{
    /// <summary>
    /// Locations Index
    /// </summary>
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public IndexModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [TempData]
        public string Message { get; set; }

        [BindProperty]
        public IList<Location> Locations { get; set; }

        public async Task OnGetAsync()
        {
            Locations = await _dbContext.Locations.
                Include(w => w.Category).
                ToListAsync();
        }

        public async Task OnGetSortByAlphabet()
        {
            Locations = await _dbContext.Locations.Include(w => w.Category).OrderBy(w => w.Adress).ToListAsync();
        }
    }
}

MyLocation002/Pages/Locations/Create.cshtml
@page
@model MyLocation002.Pages.Locations.CreateModel
@using MyLocation002.Extentions
@{
    ViewData["Title"] = "Create";
}

<h2 class="col-sm-offset-5">Create New Location</h2>



<form method="post">
    <div class="form-border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-sm-2">
                <label asp-for="LocationsVM.Locations.Name" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <input asp-for="LocationsVM.Locations.Name" class="form-control" />
            </div>
            <span asp-validation-for="LocationsVM.Locations.Name" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-sm-2">
                <label asp-for="LocationsVM.Locations.Adress" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <input asp-for="LocationsVM.Locations.Adress" class="form-control" />
            </div>
            <span asp-validation-for="LocationsVM.Locations.Adress" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-sm-2">
                <label asp-for="LocationsVM.Locations.CategoryId" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <select asp-for="LocationsVM.Locations.CategoryId" asp-items="Model.LocationsVM.Categories.ToSelectListItem(Model.LocationsVM.Locations.CategoryId)" class="form-control"></select>
            </div>
        </div>

        <br />
        <div class="form-group">
            <button type="submit" asp-page-handler="FatchCordinates" value="Get Locations" class="btn btn-info">Get Locations</button>
        </div>
    </div>
    <hr />
    <div class="form-border">
        <div class="form-group row">
            <div class="col-sm-2">
                <label asp-for="LocationsVM.Locations.Latitude" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                @if (Model.LocationsVM.Locations.Longitude != null)
                {
                    <input asp-for="LocationsVM.Locations.Latitude" value="@Model.LocationsVM.Locations.Latitude" class="form-control" />
                }
                else
                {
                    <input asp-for="LocationsVM.Locations.Latitude" disabled value="@Model.LocationsVM.Locations.Latitude" class="form-control" />

                }
            </div>

            @if (Model.LocationsVM.Locations.Latitude == null && Model.LocationsVM.Locations.Longitude == null)
            {
                <span asp-validation-for="LocationsVM.Locations.Latitude" class="text-danger"></span>
            }

        </div>
        <div class="form-group row">
            <div class="col-sm-2">
                <label asp-for="LocationsVM.Locations.Longitude" class="custom-label"></label>
            </div>
            <div class="col-sm-4">

                @if (Model.LocationsVM.Locations.Latitude != null)
                {
                    <input asp-for="LocationsVM.Locations.Longitude" value="@Model.LocationsVM.Locations.Longitude" hidden class="form-control" />
                }
                else
                {
                    <input asp-for="LocationsVM.Locations.Longitude" disabled value="@Model.LocationsVM.Locations.Longitude" hidden class="form-control" />
                }

            </div>

            @if (Model.LocationsVM.Locations.Latitude == null && Model.LocationsVM.Locations.Longitude == null)
            {
                <span asp-validation-for="LocationsVM.Locations.Longitude" hidden class="text-danger"></span>
            }

        </div>
        <div class="form-group">

            @if (Model.LocationsVM.Locations.Latitude != null && Model.LocationsVM.Locations.Longitude != null)
            {
                <input type="submit" asp-page-handler="create" value="Create" class="btn btn-success" />
            }
            else
            {
                <input type="submit" disabled asp-page-handler="create" value="Create" class="btn btn-success" />
            }

            <a asp-page="Index" class="btn btn-primary">Back to list</a>

        </div>
        <hr />
    </div>
</form>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MyLocation002/Pages/Locations/Delete.cshtml
@page
@model MyLocation002.Pages.Locations.DeleteModel
@{
    ViewData["Title"] = "Delete";
}

<h2 class="col-sm-offset-5">Delete</h2>

@if (Model.Message != null)
{
    <div class="alert alert-info alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="cencel">
            <span aria-hidden="true">&times;</span>
        </button>

        <button type="button" class="open" data-dismiss="alert" aria-label="confirm">
            <span aria-hidden="true">&times;</span>
        </button>
        @Model.Message
    </div>
}


<form method="post">
    <div class="form-border">
        <input type="hidden" asp-for="Locations.Id" />
        <fieldset disabled>
            <div class="form-group row">
                <div class="col-sm-2">
                    <label asp-for="Locations.Name" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Locations.Name" class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-2">
                    <label asp-for="Locations.Adress" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Locations.Adress" class="form-control" />
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-2">
                    <label asp-for="Locations.CategoryId" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Locations.Category.Name" class="form-control" />
                </div>
            </div>
        </fieldset>
        <br />
        <div class="form-group">
            <input type="submit" value="Delete"
                   @Html.ActionLink("", "Delete", new { id = Model.Locations.Id }, new { onclick = "return confirm('are you sure you want to delete this item?')", @class = "btn btn-sm btn-danger submit" })



            <a asp-page="Index" class="btn btn-sm btn-success">Back to list</a>
        </div>
    </div>
</form>

MyLocation002/Pages/Locations/Details.cshtml
@page "{id?}/{handler?}"
@model MyLocation002.Pages.Locations.DetailsModel
@using MyLocation002.Extentions

@{
    ViewData["Title"] = "Details";
}

<h2 class="col-sm-offset-5">Details</h2>

<hr />

<div class="form-border row">

    <div class="col-sm-8">

        <fieldset disabled>

            <div class="form-group row">

                <div class="col-sm-4">
                    <label asp-for="LocationsVM.Locations.Name" class="custom-label"></label>

                </div>
                <div class="col-sm-8">
                    <input asp-for="LocationsVM.Locations.Name" class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-4">
                    <label asp-for="LocationsVM.Locations.Adress" class="custom-label"></label>
                </div>
                <div class="col-sm-8">
                    <input asp-for="LocationsVM.Locations.Adress" class="custom-label" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-4">
                    <label asp-for="LocationsVM.Locations.Longitude" class="custom-label"></label>
                </div>
                <div class="col-sm-8">
                    <input asp-for="LocationsVM.Locations.Longitude" class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-4">
                    <label asp-for="LocationsVM.Locations.Latitude" class="custom-label"></label>
                </div>
                <div class="col-sm-8">
                    <input asp-for="LocationsVM.Locations.Latitude" class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-4">
                    <label asp-for="LocationsVM.Locations.CategoryId" class="custom-label"></label>
                </div>
                <div class="col-sm-8">
                    <select asp-for="LocationsVM.Locations.CategoryId" asp-items="Model.LocationsVM.Categories.ToSelectListItem(Model.LocationsVM.Locations.CategoryId)" class="form-control"></select>
                </div>
            </div>
        </fieldset>
    </div>

    <div class="col-sm-3">
        <div id="map_canvas" style="border-radius:5px;border :1px solid #bbb9b9;width:18vw; height:25vw;"></div>
    </div>
    <br />

    <div class="form-group row col-sm-12">
        <a asp-page="Edit" asp-route-id="@Model.Locations.Id" class="btn btn-success">Edit</a>
        <a asp-page="Index" class="btn btn-primary">Back to list</a>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDyawcavh4Ca_xDOQ_6l6QCzYdhW2aLubc"></script>

<script type="text/javascript">
    $(document).ready(function () {
        Initialize();
    });

    function Initialize() {
        google.maps.visualRefresh = true;

        var contry = new google.maps.LatLng(@Model.LocationsVM.Locations.Latitude, @Model.LocationsVM.Locations.Longitude);

        var mapOptions = {
            zoom: 17,
            center: contry,
            mapTypeId: google.maps.MapTypeId.G_NORMAL_MAP
        };

        var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);

        var data = [
            {
                "Id": @Model.LocationsVM.Locations.Id,
                "PlaceName": "@Model.LocationsVM.Locations.Name",
                "GeoLong": "@Model.LocationsVM.Locations.Latitude",
                "GeoLat": "@Model.LocationsVM.Locations.Longitude"
            }
        ];

        // Using the JQuery "each" selector to iterate through the JSON list and drop marker pins
        $.each(data, function (i, item) {
            var marker = new google.maps.Marker({
                'position': new google.maps.LatLng(item.GeoLong, item.GeoLat),
                'map': map,
                'title': item.PlaceName
            });

            // Make the marker-pin blue
            marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png');
        });
    }

</script>

MyLocation002/Pages/Locations/Edit.cshtml
@page "{id?}/{handler?}"

@model MyLocation002.Pages.Locations.EditModel
@using MyLocation002.Extentions

@{
    ViewData["Title"] = "Edit";
}

<h2 class="col-sm-offset-5">Edit</h2>

<form method="post">
    <div class="form-border">
        <div asp-validation-summary="ModelOnly" class="text-danger">
        </div>
        <input type="hidden" asp-for="LocationsVM.Locations.Id" />
        <div class="form-group row">
            <div class="col-sm-2">
                <label asp-for="LocationsVM.Locations.Name" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <input asp-for="LocationsVM.Locations.Name" class="form-control" />
            </div>
            <span asp-validation-for="LocationsVM.Locations.Name" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-sm-2">
                <label asp-for="LocationsVM.Locations.Adress" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <input asp-for="LocationsVM.Locations.Adress" class="form-control" />
            </div>
            <span asp-validation-for="LocationsVM.Locations.Adress" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-sm-2">
                <label asp-for="LocationsVM.Locations.Latitude" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <input asp-for="LocationsVM.Locations.Latitude" class="form-control" />
            </div>
            <span asp-validation-for="LocationsVM.Locations.Latitude" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-sm-2">
                <label asp-for="LocationsVM.Locations.Longitude" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <input asp-for="LocationsVM.Locations.Longitude" class="form-control" />
            </div>
            <span asp-validation-for="LocationsVM.Locations.Longitude" class="text-danger"></span>
        </div>

        <div class="form-group row">
            <div class="col-sm-2">
                <label asp-for="LocationsVM.Locations.CategoryId" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <select asp-for="LocationsVM.Locations.CategoryId" asp-items="Model.LocationsVM.Categories.ToSelectListItem(Model.LocationsVM.Locations.CategoryId)" class="form-control"></select>
            </div>

            <span asp-validation-for="LocationsVM.Locations.Category.Name" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Update" class="btn btn-sm btn-primary" />
            <a asp-page="Index" class="btn btn-sm btn-success">Back to list</a>
        </div>
    </div>
</form>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MyLocation002/Pages/Locations/Index.cshtml
@page "{id?}/{handler?}"
@model MyLocation002.Pages.Locations.IndexModel
@{
    ViewData["Title"] = "Index";
}
<br />
<h2 class="col-sm-offset-5">Locations Page</h2>
<br />

@if (Model.Message != null)
{
    <div class="alert alert-info alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Model.Message
    </div>
}
<hr />

<div class="container">
    <div class="form-border">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(m => m.Locations[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Locations[0].Adress)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Locations[0].Category.DisplayCategory)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Locations[0].Latitude)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Locations[0].Longitude)
                </th>
            </tr>

            @foreach (var location in Model.Locations)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(w => location.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(w => location.Adress)
                    </td>
                    <td>
                        @Html.DisplayFor(w => location.Category.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(w => location.Latitude)
                    </td>
                    <td>
                        @Html.DisplayFor(w => location.Longitude)
                    </td>
                    <td>
                        @Html.Partial("_TableButtonsPartital", new Data.Models.IndevidualButtonPartitial { Id = location.Id })
                    </td>

                </tr>
            }
        </table>
        <p>
            <a asp-page="Create" type="button" class="btn btn-primary btn-sm">
                <span class="glyphicon glyphicon-plus">&nbsp;Create New</span>
            </a>
            <a asp-page-handler="sortbyalphabet" type="button" class="btn btn-success btn-sm">
                <span class="glyphicon glyphicon-sort">&nbsp;Sort By Adress</span>
            </a>
        </p>
    </div>
</div>